config-version: 2
version: 2
name: my_meltano_project
profile: meltano
source-paths:
- models
- source
data-paths:
- data
analysis-paths:
- analysis
test-paths:
- tests
macro-paths:
- macros
snapshot-paths:
- snapshots
target-path: ../.meltano/transformers/dbt/target
log-path: logs
modules-path: dbt_modules
clean-targets:
- ../.meltano/transformers/dbt/target
- dbt_modules
- logs
models:
  my_meltano_project: null
