# This file is managed by the 'dbt' file bundle and updated automatically when `meltano upgrade` is run.
# To prevent any manual changes from being overwritten, remove the file bundle from `meltano.yml` or disable automatic updates:
#     meltano config --plugin-type=files dbt set _update transform/profile/profiles.yml false
config-version: 2
version: 2
config:
  send_anonymous_usage_stats: False
  use_colors: True
meltano:
  target: athena-prod
  outputs:
    athena-test:
      type: athena
      database: test_localdev
      s3_staging_dir: s3://devtest-meltano-bucket-01/dbt/
      schema: dbt
      region_name: us-east-2
    athena-prod:
      type: athena
      database: prod01
      s3_staging_dir: s3://prod-meltano-bucket-01/dbt/
      schema: dbt
      region_name: us-east-2
