config-version: 2
version: 2
config:
  send_anonymous_usage_stats: True
  use_colors: True
meltano:
  target: athena-prod
  outputs:
    athena-test:
      type: athena
      database: "{{ env_var('ATHENA_CATALOG') }}"
      schema: "{{ env_var('DBT_OUTPUT_SCHEMA_NAME') }}"
      s3_staging_dir: s3://devtest-meltano-bucket-01/dbt/
      region_name: us-east-2
    athena-prod:
      type: athena
      database: "{{ env_var('ATHENA_CATALOG') }}"
      schema: "{{ env_var('DBT_OUTPUT_SCHEMA_NAME') }}"
      s3_staging_dir: s3://prod-meltano-bucket-01/dbt/
      region_name: us-east-2
