### A CI workflow template that runs linting and python testing

name: Test hub_utils

on: [push]

jobs:
  pytest:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry==1.8.*
    - name: Clone Hub repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        repository: meltano/hub
        path: hub_repo
        ref: main
    - name: Install dependencies
      run: |
        poetry install
    - name: Test with pytest
      run: |
        HUB_ROOT_PATH=$GITHUB_WORKSPACE/hub_repo poetry run tox -e pytest
