name: nightly-netlify-build

on:
  schedule:
    - cron: "15 13 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: {}

jobs:
  build:
    name: Netlify Build
    runs-on: ubuntu-latest

    steps:
      - name: trigger netlify build
        env:
          HOOK_URL: ${{ secrets.DAILY_METRICS_REBUILD_HOOK_URL }}
        run: |
          curl -X POST -d '{}' $HOOK_URL
