name: Metadata Refresh

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment to run the workflow in'
        required: true
        type: choice
        default: 'preview'
        options:
          - 'preview'
          - 'production'
  schedule:
    - cron: '0 12 * * 1' # Run at midnight UTC on Mondays

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: {}

jobs:
  metadata_refresh:
    name: Metadata Refresh
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || github.event_name == 'schedule' && 'production' || 'preview' }}
    env:
      AWS_S3_BUCKET: "${{ secrets.HUB_METADATA_S3_BUCKET }}"
    permissions:
      id-token: write # This is required for requesting the JWT
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@254c19bd240aabef8777f48595e9d2d7b972184b # v6.2.1
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        aws-region: us-west-2
        role-session-name: "GitHubActions"

    - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0

    - name: Install hub-utils
      run: uv tool install ./hub-utils

    - name: Download Raw JSON Output
      run: hub-utils download-metadata "/home/runner/work/downloaded_data" --ignore-list-str="extractors/tap-ga4/connorflyn,extractors/tap-ga4/meltanolabs,extractors/tap-ga4/sehnem,extractors/tap-salesforce-commerce/hotgluexyz,loaders/target-s3/crowemi,loaders/target-s3-parquet/jkausti,extractors/tap-rest-api-msdk/widen,extractors/tap-mailchimp/acarter24,extractors/tap-msaccess/matatika,extractors/tap-totango/edsoncezar16"

    - name: Merge Raw JSON and Existing Definition
      run: hub-utils merge-metadata $(pwd) "/home/runner/work/downloaded_data"

    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
      with:
        token: ${{ secrets.MELTYBOT_GITHUB_AUTH_TOKEN }}
        commit-message: Refresh plugin metadata ${{ steps.date.outputs.date }}
        committer: GitHub <noreply@github.com>
        author: MeltyBot <MeltyBot@users.noreply.github.com>
        signoff: false
        branch: hub-bot-metadata-${{ steps.date.outputs.date }}-${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}
        delete-branch: true
        title: 'chore: [Hub Bot] Refresh metadata ${{ steps.date.outputs.date }}'
        body: |
          Updates Plugin Definitions
        assignees: edgarrmondragon
        reviewers: edgarrmondragon
        draft: false
